/*
Copyright (c) 2011 Jonnas Fonini <contato@fonini.net>

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/

CKEDITOR.dialog.add( 'youtube', function( editor )
{
	return {
		title : 'Insert Youtube Video',
		minWidth : 390,
		minHeight : 230,
		contents : [
		{
			id : 'urlTab',
			label : 'Video URL',
			title : 'Video URL',
			elements :
			[
				{
					id : 'url',
					type : 'text',
					label : 'Paste the URL of the YouTube video'
				},
				{
					id : 'xhtml',
					type : 'checkbox',
					label : 'XHTML validate'
				},
				{
					id : 'width',
					type : 'text',
					label : 'width',
					width : '40',
					default: '425'
				},
				{
					id : 'height',
					type : 'text',
					label : 'height',
					width : '40',
					default: '349'
				}
			]
		},
		{
			id : 'embedTab',
			label : 'Embed Code',
			title : 'Embed Code',
			elements :
			[
				{
					id : 'embed',
					type : 'textarea',
					label : 'Paste the code generated by YouTube (embed)'
				}
			]
		}
        ],
		onOk : function() {
			var editor = this.getParentEditor();
			var contentUrl = this.getValueOf( 'urlTab', 'url' );
			var contentEmbed = this.getValueOf( 'embedTab', 'embed' );
			var xhtml = this.getValueOf( 'urlTab', 'xhtml' );
			var width = this.getValueOf( 'urlTab', 'width' );
			var height = this.getValueOf( 'urlTab', 'height' );

			width = width ? width : 450;
			height = height ? height : 366;
					
			if ( contentUrl.length > 0 ) {
				if (xhtml == true){
					contentUrl = contentUrl.replace(/^[^v]+v.(.{11}).*/,"$1");
					editor.insertHtml('<object type="application/x-shockwave-flash" style="width:' + width + 'px; height:' + height + 'px;" data="http://www.youtube.com/v/'+contentUrl+'"><param name="movie" value="http://www.youtube.com/v/'+contentUrl+'" /></object>');
				}
				else {
					contentUrl = contentUrl.replace(/^[^v]+v.(.{11}).*/, "$1");
					editor.insertHtml('<object width="' + width + '" height="' + height + '"><param name="movie" value="http://www.youtube.com/v/'+contentUrl+'"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/'+contentUrl+'" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="' + width + '" height="' + height + '"></embed></object>');
				}
			}	
			else
			if ( contentEmbed.length > 0 ) {
				editor.insertHtml(contentEmbed);						
			}
		},
	buttons : [ CKEDITOR.dialog.okButton, CKEDITOR.dialog.cancelButton ]
	};
} );


CKEDITOR.plugins.add( 'youtube',
{
	init : function( editor )
	{
		var command = editor.addCommand( 'youtube', new CKEDITOR.dialogCommand( 'youtube' ) );
		command.modes = { wysiwyg:1, source:1 };
		command.canUndo = false;

		editor.ui.addButton( 'YouTube',
		{
			label : 'Insert Youtube Video',
			command : 'youtube',
			icon : this.path + 'youtube.png'
		});

		CKEDITOR.dialog.add( 'youtube', 'youtube' );
	}
});
